### ISSUE TITLE
Improve Nav Bar Design

### ISSUE THREAD

**Issue by debuuuu007** [swarnade/webdesign-switch#10]
I want to change the design of Navbar. You can assign me under JWOC'24.

**Comment by swarnade** [comment]
Plz Raise Issue After 15th From Your Side .Mentee Can Raise Issue , Only After 15th Janauary . Till Then Keep a Close Look On The Issue Raised By The Project Mentor.

**Comment by swarnade** [comment]
@debuuuu007 U Can Start Raisng Issue Now
