### ISSUE TITLE
Redesign The NavBar For The Website

### ISSUE THREAD

**Issue by swarnade** [swarnade/webdesign-switch#12]
Redesign The NavBar For The Website

**Comment by Seema-bedara** [comment]
Hi,                                                                                                                                                                                                                           I am from JWoC'24 .                                                                                                                                                                                                            I am interested in contributing to this as a part of JWOC.`24 Please assign it to me.

**Comment by Ananyamishra08** [comment]
Hello, @swarnade 
I would like to work on this , please assign it to me.

**Comment by swarnade** [comment]
@Seema-bedara Go For Simple Minimalist Navbar Design

**Comment by swarnade** [comment]
@Ananyamishra08 Raise an New Issue

**Comment by DarshSohaliya** [comment]
I would like to work on that issue under JWOC
