### ISSUE TITLE
Design The Minimalist Logo For The Site 

### ISSUE THREAD

**Issue by swarnade** [swarnade/webdesign-switch#13]
Design The Minimalist Logo For The Site

**Comment by Ananyamishra08** [comment]
Hello, @swarnade  I would like to work on this , please assign it to me.

**Comment by Hacxmr** [comment]
Hey @swarnade, I am interested in contributing to the design of the logo. Can you assign this task to me under JWOC?

**Comment by swarnade** [comment]
@Ananyamishra08 Go For It

**Comment by Ananyamishra08** [comment]
pls assign this to me under jwoc

**Comment by DarshSohaliya** [comment]
I would like to work on that issue under JWOC

**Comment by hittie45** [comment]
Hey @swarnade I would like to contribute on this issue under JWOC

**Comment by swarnade** [comment]
Closes Issue #56
