### ISSUE TITLE
Design a Navabar

### ISSUE THREAD

**Issue by swarnade** [swarnade/webdesign-switch#14]
Design a Navabar

**Comment by shahil-afroz** [comment]
Can you assign this to me...under JWOC 24...

**Comment by Divyanshgarg-04** [comment]
@swarnade I would love to work on this issue. Can you please assign this issue to me under JWOC'24

**Comment by swarnade** [comment]
@shahil-afroz Go For It

**Comment by shahil-afroz** [comment]
What kind of changes will you expect?
Any suggestions?

**Comment by swarnade** [comment]
Nothing Exactly
