### ISSUE TITLE
Add a more customized button.

### ISSUE THREAD

**Issue by Sruti-sahini** [swarnade/webdesign-switch#15]
I have a quite createful imagination of more customized button style.
Please assign me this issue under JWoC'24

**Comment by ogshashwat17** [comment]
i want  to contribute

**Comment by swarnade** [comment]
@ogshashwat17 This Issue Is Already Issue, U can Raise another New issue To Create Ur Own Button

**Comment by Sruti-sahini** [comment]
@swarnade I have raised PR.
Please and review it.

**Comment by swarnade** [comment]
Great Work
