### ISSUE TITLE
Hover option addition to the nav bar, and the info selection doesnt lead anywhere

### ISSUE THREAD

**Issue by thesri** [swarnade/webdesign-switch#17]
Hover option addition in the sense chaging the color a little bit so that we can differentiate it , and by selecting info from the nav bar it doesnt lead anywhere, the link is broken ig. Please assign me this issue under JWOC 20224

**Comment by swarnade** [comment]
@thesri Will u Able To Redesign The  Full Navbar ?

**Comment by thesri** [comment]
yes, please do specify what features are required

**Comment by swarnade** [comment]
Design a Simple minimalistic Navbar For The Website
Any Other Tab That We Can Include jut Like Button's

**Comment by swarnade** [comment]
2-3 Days

**Comment by thesri** [comment]
should i make the pages of designs and info also ?

**Comment by thesri** [comment]
> should i make the pages of designs and info also ?

@swarnade

**Comment by swarnade** [comment]
As Of Now , No

**Comment by swarnade** [comment]
U cn raise Another issue in Future

Will look into it For Sure

**Comment by thesri** [comment]
> U cn raise Another issue in Future
> 
> 
> 
> Will look into it For Sure

Okay thanks

**Comment by swarnade** [comment]
Closes PR #52
