### ISSUE TITLE
customization of send btn 

### ISSUE THREAD

**Issue by FazeenIjaz** [swarnade/webdesign-switch#172]
The send button in the feedback form looks like 
![image](https://github.com/swarnade/webdesign-switch/assets/144797618/4b81ea22-4491-4a4f-812c-3ee02e5cfe8c)
I want to customize it a little to look like
![image](https://github.com/swarnade/webdesign-switch/assets/144797618/9c287240-1e6c-40c1-a3aa-30518aec93c6)
pls assign it to me under  JWOC'2024

**Comment by kaif969** [comment]
please assign it to me under JWOC'2024.
