### ISSUE TITLE
Improving the CSS of the page and adding more button styles 

### ISSUE THREAD

**Issue by ayesha-2101** [swarnade/webdesign-switch#18]
The first issue that I want to resolve is that of overflow
![Screenshot 2024-01-14 105854](https://github.com/swarnade/webdesign-switch/assets/112239598/cce83596-5dbb-4c9d-bbe0-d157719dca4b)
Apart from this I want to add some more button styles that will be useful for the user

**Comment by ayesha-2101** [comment]
@swarnade please assign it to me

**Comment by swarnade** [comment]
@ayesha-2101 Go For It Under JWOC . Do Not Modify the HTML File. Do Modify Only The CSS

**Comment by swarnade** [comment]
For This Only Go For Modifying The CSS Of The Box. Only

**Comment by ayesha-2101** [comment]
![Screenshot 2024-01-17 090134](https://github.com/swarnade/webdesign-switch/assets/112239598/b066d945-ef80-48b9-832d-67b64f53bc42)
I have added the glow effect to the current box where the user is hovering. 
Apart from this, I have added two new button styles. Should I proceed with the pull request @swarnade ?

**Comment by ayesha-2101** [comment]
https://github.com/swarnade/webdesign-switch/assets/112239598/ec06e164-35a9-4066-90f9-7db9f1a1e550

Left Slider button @swarnade

**Comment by swarnade** [comment]
issue #46 Close
