### ISSUE TITLE
Hover option addition to the nav bar, and the info selection doesnt lead anywhere 

### ISSUE THREAD

**Issue by thesri** [swarnade/webdesign-switch#2]
Hover option addition in the sense chaging the color a little bit so that we can differentiate it , and by selecting info from the nav bar it doesnt lead anywhere, the link is broken ig. Please assign me this issue under JWOC 20224

**Comment by swarnade** [comment]
Plz Raise Issue After 15th From Your Side .Mentee Can Raise Issue , Only After 15th Janauary . Till Then Keep a Close Look On The Issue Raised By The Project Mentor.
