### ISSUE TITLE
Icons going out of bound

### ISSUE THREAD

**Issue by Ananyamishra08** [swarnade/webdesign-switch#20]
The LinkedIn and GitHub icons are available right out of the box.

![photo](https://github.com/swarnade/webdesign-switch/assets/98649189/07601362-0002-4c41-bfde-f51d1a2724aa)

Therefore, this needs to be changed to improve the user-friendliness of the website.

**Comment by Ananyamishra08** [comment]
@swarnade i want to work on this issue under jwoc

**Comment by swarnade** [comment]
This issue Already Exists #18
