### ISSUE TITLE
ADD: Change the font type of button container

### ISSUE THREAD

**Issue by riyatyag-6** [swarnade/webdesign-switch#21]
Hey, I want to change the type of font that is inside each container.
Kindly assign this issue to me.
Thanks

**Comment by swarnade** [comment]
Okh @riyatyag-6 Go For It , Only Make To Change the CSS File . Not the HTML Files

**Comment by riyatyag-6** [comment]
Sure

**Comment by swarnade** [comment]
@riyatyag-6 Do It ASAP

**Comment by riyatyag-6** [comment]
Will complete by today EOD.

**Comment by swarnade** [comment]
@riyatyag-6 Any Update

**Comment by riyatyag-6** [comment]
PR #86 is merged. You can close it now.
