### ISSUE TITLE
CREATE FEEDBACK PAGE

### ISSUE THREAD

**Issue by Rajat-24227** [swarnade/webdesign-switch#22]
I can create an feedback page for website where users can send feedback to the designer using (HTML and CSS).

**Comment by swarnade** [comment]
@Rajat-24227 Go For It

**Comment by thatguywhocode** [comment]
Hey @swarnade , please assign me this issue under JWOC.

**Comment by Hacxmr** [comment]
Hey! @swarnade I would like to contribute on this issue if it has not been resolved yet
