### ISSUE TITLE
Create a different style button

### ISSUE THREAD

**Issue by rupalimkrishnan** [swarnade/webdesign-switch#25]
I would like to work on a new button style.Kindly assign me this issue under Jwoc'24

**Comment by pranjal12-web** [comment]
hey @swarnade please assign this issue under JWoC'24

**Comment by swarnade** [comment]
@rupalimkrishnan Go For It

**Comment by swarnade** [comment]
@pranjal12-web Just Raise a New Issue To Create a New Button

**Comment by pranjal12-web** [comment]
Sure @swarnade

**Comment by swarnade** [comment]
Merged #36
