### ISSUE TITLE
Adding 10 new creative buttons with hover effects

### ISSUE THREAD

**Issue by nandita27iitp** [swarnade/webdesign-switch#41]
@swarnade Pls assign this issue under JWOC

**Comment by swarnade** [comment]
Go For It

**Comment by nandita27iitp** [comment]
![image](https://github.com/swarnade/webdesign-switch/assets/94813932/64ac79c6-97e2-4fc4-8c96-15a3d77c25b8)

@swarnade pls review it

**Comment by swarnade** [comment]
That'sGreat @nandita27iitp , U Caan Raise PR For It

**Comment by swarnade** [comment]
PR #58 Merged
