### ISSUE TITLE
Add two new Creative Buttons with Animated Hover Effects

### ISSUE THREAD

**Issue by zul132** [swarnade/webdesign-switch#53]
I would like to add two new creative and visually appealing Buttons with hover animations.

Button 1:
![btn1_before](https://github.com/swarnade/webdesign-switch/assets/98112914/1ba5c3d5-a41c-4422-a0ab-e02f68583bfe)
![btn1_after](https://github.com/swarnade/webdesign-switch/assets/98112914/f69364ef-022e-4e11-afab-6ee11764cb3f)

Button 2:
![btn2_before](https://github.com/swarnade/webdesign-switch/assets/98112914/002e85bf-6fd3-4b55-8932-66d79484add2)
![btn2_after](https://github.com/swarnade/webdesign-switch/assets/98112914/cf3f317c-24a6-41dd-9db9-5bcea719103a)

Kindly assign me this issue under JWOC

**Comment by swarnade** [comment]
@zul132 Go For It

**Comment by zul132** [comment]
@swarnade I have created the PR #61

**Comment by swarnade** [comment]
PR Merged #61
