### ISSUE TITLE
Change dark mode to light mode with toggle button

### ISSUE THREAD

**Issue by shahil-afroz** [swarnade/webdesign-switch#6]
![WhatsApp Image 2024-01-11 at 18 25 12_5722ca10](https://github.com/swarnade/webdesign-switch/assets/137023904/5ce1a75e-c490-4aee-b550-78e9b42a8395)
![WhatsApp Image 2024-01-11 at 18 25 12_c0e9a0ee](https://github.com/swarnade/webdesign-switch/assets/137023904/197b7865-9098-425e-b04b-563e1e30c311)
 
like this web site ....we can change dark mode to light mode with the help of toggle button....
Can you assign this to me when the coding phase of JWOC 24 started.

**Comment by subhasmita223** [comment]
hey!  when JWOC 24 would start. can you pls  assign this problem to me . i can make the necessary changes .

**Comment by swarnade** [comment]
Plz Raise Issue After 15th From Your Side .Mentee Can Raise Issue , Only After 15th Janauary . Till Then Keep a Close Look On The Issue Raised By The Project Mentor.

**Comment by shahil-afroz** [comment]
But in other projects mentors not only permit to raise an issue by mantee
but also assigns them to do it.... So it's also against the rule??

**Comment by swarnade** [comment]
Yaa Absolutely

**Comment by swarnade** [comment]
Just Raise An Issue on 15th January 00:01
