### ISSUE TITLE
New style button with hover effect

### ISSUE THREAD

**Issue by shahil-afroz** [swarnade/webdesign-switch#69]
![Screenshot 2024-01-20 015718](https://github.com/swarnade/webdesign-switch/assets/137023904/d1fa4b21-82ee-4925-af70-0ffa3497c403)
![Screenshot 2024-01-20 015736](https://github.com/swarnade/webdesign-switch/assets/137023904/7367e922-cca1-4870-b245-f31620089b96)

like this picture when we hover in the the 1st button then  2nd button appear.......

Can you assign this issue to me under JWOC 24.....I wand to add this button to your project

**Comment by swarnade** [comment]
@shahil-afroz Go For It
