### ISSUE TITLE
Fix the margin and Display.....

### ISSUE THREAD

**Issue by shahil-afroz** [swarnade/webdesign-switch#7]
![image](https://github.com/swarnade/webdesign-switch/assets/137023904/232274df-6a0b-4c34-ad44-ff9e18f59947)

In this page the button and  information are so closely attached.
so I can fix this issue.....can you assign this to me when the coding phase of JWOC 24 will be started.

**Comment by swarnade** [comment]
Plz Raise Issue After 15th From Your Side .Mentee Can Raise Issue , Only After 15th Janauary . Till Then Keep a Close Look On The Issue Raised By The Project Mentor.
