### ISSUE TITLE
Addition of Save Button 

### ISSUE THREAD

**Issue by TanushreeBorase** [swarnade/webdesign-switch#73]
I would like to add a save button. PLease assign me under JWOC'24

<img width="132" alt="image" src="https://github.com/swarnade/webdesign-switch/assets/130696335/b894b414-d2f1-48d7-af3f-3cd43c8da8fd">

on hovering 
<img width="142" alt="image" src="https://github.com/swarnade/webdesign-switch/assets/130696335/085e1056-0e77-49a3-9e41-161f79fc6360">

**Comment by swarnade** [comment]
Great Button @TanushreeBorase Go For It

**Comment by vermaanurag1532** [comment]
please Assign it to me
