### ISSUE TITLE
Improving the CSS of the page and adding more button styles 

### ISSUE THREAD

**Issue by ayesha-2101** [swarnade/webdesign-switch#9]
@swarnade I am a student of IIT Patna, and I am willing to contribute to this under JWOC. Can you assign this to me once the coding period starts?
The first issue that I want to resolve is that of overflow 
![Screenshot 2024-01-14 105854](https://github.com/swarnade/webdesign-switch/assets/112239598/f9cdaba7-3990-4886-a79d-c858035cd3c1)
Apart from this I want to improve the overall CSS of the page 
The third is I want to add some more button styles that will be useful for the user

**Comment by rupalimkrishnan** [comment]
I would like to work on this issue

**Comment by ogshashwat17** [comment]
can you elabrote more about the button styling you want

**Comment by rupalimkrishnan** [comment]
> can you elabrote more about the button styling you want

I would like to add an aqua color button with a direction aware hovering effect.

**Comment by swarnade** [comment]
Hey @ayesha-2101  Just Raise The Issue After 15th Jan 00:01 I Will Be Assigning It To U

**Comment by swarnade** [comment]
@ayesha-2101 @rupalimkrishnan @ogshashwat17 U Can Starting Raising Issue Now
