### ISSUE TITLE
Create an info page 

### ISSUE THREAD

**Issue by thesri** [swarnade/webdesign-switch#98]
We can create an info page which will contain information about which button created by which person , or the general info of the website or the info of the maker of website . please assign this issue under jwoc 2024

**Comment by vermaanurag1532** [comment]
please Assign it to me

**Comment by swarnade** [comment]
@thesri Go For It

**Comment by thesri** [comment]
> > @thesri Go For It
> 
> Should I work on it? Or is it completed 

@swarnade 🥲🥲should I work on it ??

**Comment by thesri** [comment]
> > > @thesri Go For It
> > 
> > 
> > Should I work on it? Or is it completed
> 
> @swarnade 🥲🥲should I work on it ??

@swarnade why was it closed?
